### ISSUE TITLE
main.sh script throw an error after entering the password for the p12 file

### ISSUE THREAD

**Issue by pchithapuram1** [EntrustCorporation/pki-utilities#1]
The script thows an error pertaining legacy flag used with openssl command in the script, right after the password for p12 file is captured. It seems to get past that error once I remove the flag. I am using RHEL 8.9. Bash is at a version in the range mentioned in the documentation. jq is there. Curl is at version level  below what was mentioned
![main_sh_legacy_flag_error](https://github.com/EntrustCorporation/pki-utilities/assets/163223235/5fc612f2-0798-40dd-a6bc-800154706a07)

**Comment by WantTrueNerds** [comment]
The legacy flag was added to support P12 files which were generated using older versions of OpenSSL whenever a newer version of OpenSSL is being used.

I'll get the script updated so that it works with either new or old versions of OpenSSL.

In the meantime, you can still use the script by removing the `-legacy` flag from Line 24: https://github.com/EntrustCorporation/pki-utilities/blob/main/cagw-shell-util/main.sh#L24

**Comment by andrew-entrust** [comment]
@pchithapuram1: The latest working copy of the script has been fixed to work with both old and new versions of OpenSSL.

Download from here: https://raw.githubusercontent.com/EntrustCorporation/pki-utilities/main/cagw-shell-util/main.sh

**Comment by WantTrueNerds** [comment]
@pchithapuram1: The latest working copy of the script has been fixed to work with both old and new versions of OpenSSL.

Download from here: https://raw.githubusercontent.com/EntrustCorporation/pki-utilities/main/cagw-shell-util/main.sh
